# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menuBar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(437, 64)
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.import_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.import_checkBox.setGeometry(QtCore.QRect(10, 10, 231, 19))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.import_checkBox.setFont(font)
        self.import_checkBox.setChecked(True)
        self.import_checkBox.setObjectName("import_checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 437, 26))
        self.menubar.setObjectName("menubar")
        self.menu_N = QtWidgets.QMenu(self.menubar)
        self.menu_N.setObjectName("menu_N")
        self.menu_E = QtWidgets.QMenu(self.menubar)
        self.menu_E.setObjectName("menu_E")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuOthers_O = QtWidgets.QMenu(self.menubar)
        self.menuOthers_O.setObjectName("menuOthers_O")
        self.menuMorphology_2 = QtWidgets.QMenu(self.menubar)
        self.menuMorphology_2.setObjectName("menuMorphology_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMaximumSize(QtCore.QSize(16777215, 0))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_wl_hist = QtWidgets.QAction(MainWindow)
        self.action_wl_hist.setObjectName("action_wl_hist")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_zoom = QtWidgets.QAction(MainWindow)
        self.action_zoom.setObjectName("action_zoom")
        self.action_detail_enhancement = QtWidgets.QAction(MainWindow)
        self.action_detail_enhancement.setObjectName("action_detail_enhancement")
        self.action_fourier_spectrum = QtWidgets.QAction(MainWindow)
        self.action_fourier_spectrum.setObjectName("action_fourier_spectrum")
        self.action_filter_spectrum = QtWidgets.QAction(MainWindow)
        self.action_filter_spectrum.setEnabled(True)
        self.action_filter_spectrum.setObjectName("action_filter_spectrum")
        self.action_histogram_equalization = QtWidgets.QAction(MainWindow)
        self.action_histogram_equalization.setObjectName("action_histogram_equalization")
        self.action_laplacian = QtWidgets.QAction(MainWindow)
        self.action_laplacian.setObjectName("action_laplacian")
        self.action_median_filter = QtWidgets.QAction(MainWindow)
        self.action_median_filter.setObjectName("action_median_filter")
        self.action_line_transfer = QtWidgets.QAction(MainWindow)
        self.action_line_transfer.setObjectName("action_line_transfer")
        self.action_gama_transfer = QtWidgets.QAction(MainWindow)
        self.action_gama_transfer.setObjectName("action_gama_transfer")
        self.action_seg_augment = QtWidgets.QAction(MainWindow)
        self.action_seg_augment.setObjectName("action_seg_augment")
        self.actionErode = QtWidgets.QAction(MainWindow)
        self.actionErode.setObjectName("actionErode")
        self.actionDilate = QtWidgets.QAction(MainWindow)
        self.actionDilate.setObjectName("actionDilate")
        self.actionDivide_Border = QtWidgets.QAction(MainWindow)
        self.actionDivide_Border.setObjectName("actionDivide_Border")
        self.action_erode = QtWidgets.QAction(MainWindow)
        self.action_erode.setObjectName("action_erode")
        self.action_dilate = QtWidgets.QAction(MainWindow)
        self.action_dilate.setObjectName("action_dilate")
        self.action_divide_border = QtWidgets.QAction(MainWindow)
        self.action_divide_border.setObjectName("action_divide_border")
        self.menu_N.addAction(self.action_open)
        self.menu_N.addAction(self.action_save)
        self.menu_E.addAction(self.action_wl_hist)
        self.menu_E.addAction(self.action_zoom)
        self.menu_E.addAction(self.action_detail_enhancement)
        self.menu.addAction(self.action_fourier_spectrum)
        self.menu.addAction(self.action_filter_spectrum)
        self.menuOthers_O.addAction(self.action_laplacian)
        self.menuOthers_O.addAction(self.action_median_filter)
        self.menuOthers_O.addSeparator()
        self.menuOthers_O.addAction(self.action_histogram_equalization)
        self.menuOthers_O.addSeparator()
        self.menuOthers_O.addAction(self.action_line_transfer)
        self.menuOthers_O.addAction(self.action_gama_transfer)
        self.menuOthers_O.addAction(self.action_seg_augment)
        self.menuMorphology_2.addAction(self.action_erode)
        self.menuMorphology_2.addAction(self.action_dilate)
        self.menuMorphology_2.addAction(self.action_divide_border)
        self.menubar.addAction(self.menu_N.menuAction())
        self.menubar.addAction(self.menu_E.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuOthers_O.menuAction())
        self.menubar.addAction(self.menuMorphology_2.menuAction())

        self.retranslateUi(MainWindow)
        self.action_open.triggered.connect(MainWindow.openfile) # type: ignore
        self.action_wl_hist.triggered.connect(MainWindow.wl_hist) # type: ignore
        self.action_save.triggered.connect(MainWindow.savefile) # type: ignore
        self.action_zoom.triggered.connect(MainWindow.set_zoom) # type: ignore
        self.action_detail_enhancement.triggered.connect(MainWindow.detail_enhancement) # type: ignore
        self.action_fourier_spectrum.triggered.connect(MainWindow.show_fourier_spectrum) # type: ignore
        self.action_filter_spectrum.triggered.connect(MainWindow.show_filter_spectrum) # type: ignore
        self.action_histogram_equalization.triggered.connect(MainWindow.action_histogram_equalization) # type: ignore
        self.action_laplacian.triggered.connect(MainWindow.action_laplacian) # type: ignore
        self.action_median_filter.triggered.connect(MainWindow.action_median_filter) # type: ignore
        self.action_line_transfer.triggered.connect(MainWindow.action_line_transfer) # type: ignore
        self.action_gama_transfer.triggered.connect(MainWindow.action_gama_transfer) # type: ignore
        self.action_seg_augment.triggered.connect(MainWindow.action_seg_augment) # type: ignore
        self.action_erode.triggered.connect(MainWindow.action_erode_img) # type: ignore
        self.action_dilate.triggered.connect(MainWindow.action_dilate_img) # type: ignore
        self.action_divide_border.triggered.connect(MainWindow.action_divide_border) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ImageLu"))
        self.import_checkBox.setText(_translate("MainWindow", "Don\'t Show Import Options"))
        self.menu_N.setTitle(_translate("MainWindow", "File (&N)"))
        self.menu_E.setTitle(_translate("MainWindow", "Edit (&E)"))
        self.menu.setTitle(_translate("MainWindow", "Display (&D)"))
        self.menuOthers_O.setTitle(_translate("MainWindow", "Others(&O)"))
        self.menuMorphology_2.setTitle(_translate("MainWindow", "Morphology"))
        self.action_open.setText(_translate("MainWindow", "Open"))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_wl_hist.setText(_translate("MainWindow", "Window/Level"))
        self.action_save.setText(_translate("MainWindow", "Save"))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_zoom.setText(_translate("MainWindow", "Zoom"))
        self.action_detail_enhancement.setText(_translate("MainWindow", "Detail Enhancement"))
        self.action_fourier_spectrum.setText(_translate("MainWindow", "Fourier Spectrum"))
        self.action_filter_spectrum.setText(_translate("MainWindow", "Filter Spectrum"))
        self.action_histogram_equalization.setText(_translate("MainWindow", "Histogram equalization"))
        self.action_laplacian.setText(_translate("MainWindow", "Laplacian"))
        self.action_median_filter.setText(_translate("MainWindow", "Median Filter"))
        self.action_line_transfer.setText(_translate("MainWindow", "Line Transfer"))
        self.action_gama_transfer.setText(_translate("MainWindow", "Gama Transfer"))
        self.action_seg_augment.setText(_translate("MainWindow", "Seg Augment"))
        self.actionErode.setText(_translate("MainWindow", "Erode"))
        self.actionDilate.setText(_translate("MainWindow", "Dilate"))
        self.actionDivide_Border.setText(_translate("MainWindow", "Divide Border"))
        self.action_erode.setText(_translate("MainWindow", "Erode"))
        self.action_dilate.setText(_translate("MainWindow", "Dilate"))
        self.action_divide_border.setText(_translate("MainWindow", "Divide Border"))
