# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wl_hist.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 415)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hist_view = PlotWidget(self.centralwidget)
        self.hist_view.setAutoFillBackground(False)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.hist_view.setBackgroundBrush(brush)
        self.hist_view.setObjectName("hist_view")
        self.verticalLayout.addWidget(self.hist_view)
        self.level_slider = QtWidgets.QSlider(self.centralwidget)
        self.level_slider.setMinimum(1)
        self.level_slider.setMaximum(4096)
        self.level_slider.setProperty("value", 2048)
        self.level_slider.setOrientation(QtCore.Qt.Horizontal)
        self.level_slider.setInvertedAppearance(True)
        self.level_slider.setInvertedControls(True)
        self.level_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.level_slider.setTickInterval(10)
        self.level_slider.setObjectName("level_slider")
        self.verticalLayout.addWidget(self.level_slider)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.level_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.level_label.setFont(font)
        self.level_label.setObjectName("level_label")
        self.horizontalLayout_2.addWidget(self.level_label, 0, QtCore.Qt.AlignHCenter)
        self.level_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.level_lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.level_lineEdit.setFont(font)
        self.level_lineEdit.setObjectName("level_lineEdit")
        self.horizontalLayout_2.addWidget(self.level_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.window_slider = QtWidgets.QSlider(self.centralwidget)
        self.window_slider.setMinimum(2)
        self.window_slider.setMaximum(8192)
        self.window_slider.setProperty("value", 4096)
        self.window_slider.setOrientation(QtCore.Qt.Horizontal)
        self.window_slider.setInvertedAppearance(True)
        self.window_slider.setInvertedControls(True)
        self.window_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.window_slider.setTickInterval(10)
        self.window_slider.setObjectName("window_slider")
        self.verticalLayout.addWidget(self.window_slider)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.window_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.window_label.setFont(font)
        self.window_label.setObjectName("window_label")
        self.horizontalLayout_3.addWidget(self.window_label, 0, QtCore.Qt.AlignHCenter)
        self.window_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.window_lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.window_lineEdit.setFont(font)
        self.window_lineEdit.setObjectName("window_lineEdit")
        self.horizontalLayout_3.addWidget(self.window_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.wl_hist_reset = QtWidgets.QPushButton(self.centralwidget)
        self.wl_hist_reset.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.wl_hist_reset.setFont(font)
        self.wl_hist_reset.setObjectName("wl_hist_reset")
        self.horizontalLayout_4.addWidget(self.wl_hist_reset)
        self.wl_hist_conf = QtWidgets.QPushButton(self.centralwidget)
        self.wl_hist_conf.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.wl_hist_conf.setFont(font)
        self.wl_hist_conf.setObjectName("wl_hist_conf")
        self.horizontalLayout_4.addWidget(self.wl_hist_conf)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMaximumSize(QtCore.QSize(0, 0))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.level_slider.actionTriggered['int'].connect(MainWindow.level_changed) # type: ignore
        self.window_slider.actionTriggered['int'].connect(MainWindow.window_changed) # type: ignore
        self.level_lineEdit.returnPressed.connect(MainWindow.lineEdit_level) # type: ignore
        self.window_lineEdit.returnPressed.connect(MainWindow.lineEdit_window) # type: ignore
        self.wl_hist_conf.clicked.connect(MainWindow.close) # type: ignore
        self.wl_hist_reset.clicked.connect(MainWindow.reset_wl_hist) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "W&L"))
        self.level_label.setText(_translate("MainWindow", "Level:"))
        self.level_lineEdit.setText(_translate("MainWindow", "2048"))
        self.window_label.setText(_translate("MainWindow", "Window:"))
        self.window_lineEdit.setText(_translate("MainWindow", "4096"))
        self.wl_hist_reset.setText(_translate("MainWindow", "Reset"))
        self.wl_hist_conf.setText(_translate("MainWindow", "Conf"))
from pyqtgraph import PlotWidget
